from sconsproject import helpers

# Bring in the SCons environment.
Import('env')

# Declare subdirectories.
sub_dirs = []

# Define destination subdirectory, i.e. where these binaries will
# be placed.
dst_dir = '#' + env['BUILD'] + '/bin/'

# Define libraries to use.
libs = ['modules', 'base'] + env.get('LIBS', [])

# Declare local sources. Format is:
#
#   ('<binary name>', '<source 0>', '<source 1>', ...)
sources = [
#    ('lightcone', 'lightcone.cc',),
#    ('filter', 'filter.cc',),
#    ('skymaker', 'skymaker.cc',),
]

# Call the helper.
execfile(helpers.get_build_apps_script(), globals())
