from sconsproject import helpers

# Bring in the SCons environment.
Import('env')

# Declare subdirectories.
sub_dirs = []

# Define destination subdirectory, i.e. where these binaries will
# be placed.
dst_dir = '#' + env['BUILD'] + '/bin/'

# Define libraries to use.
libs = [] + env.get('LIBS', [])

# Need to build some intermediates.
utils_o = env.Object('utils.cc')

# Declare local sources. Format is:
#
#   ('<binary name>', '<source 0>', '<source 1>', ...)
sources = [
    ('bolshoi_forest_sizes', 'bolshoi_forest_sizes.cc', utils_o),
    ('bolshoi_preprocess', 'bolshoi_preprocess.cc', utils_o),
    ('bolshoi_convert', 'bolshoi_convert.cc'),
    ('bolshoi_convert2', 'bolshoi_convert2.cc', 'exporter.cc'),
]

# Call the helper.
execfile(helpers.get_build_apps_script(), globals())
