from sconsproject import helpers

# Bring in the SCons environment.
Import('env')

# Declare subdirectories.
sub_dirs = ['bolshoi']

# Define destination subdirectory, i.e. where these binaries will
# be placed.
dst_dir = '#' + env['BUILD'] + '/bin/'

# Define libraries to use.
libs = ['tao'] + env.get('LIBS', [])

# Declare local sources. Format is:
#
#   ('<binary name>', '<source 0>', '<source 1>', ...)
sources = [
    ('tao', 'tao.cc', 'application.cc'),
    ('chiara', 'chiara.cc'),
    ('generate', 'generate.cc'),
    ('milreader', 'milreader.cc'),
    ('sagereader', 'sagereader.cc'),
    ('sagecheck', 'sagecheck.cc'),
    ('subfind_check', 'subfind_check.cc'),
#    ('dbcheck', 'dbcheck.cc'),
    ('sageimport', 'sageimport.cc'),
    ('sage_import_ages', 'sage_import_ages.cc'),
    ('sage_to_hdf5', 'sage_to_hdf5.cc'),
    ('subfind_to_hdf5', 'subfind_to_hdf5.cc'),
    ('add_tree_info', 'add_tree_info.cc'),
    ('tree_view', 'tree_view.cc'),
#    ('max_test', 'max_test.cc'),
]

# Call the helper.
execfile(helpers.get_build_apps_script(), globals())
