from sconsproject import helpers

# Bring in the SCons environment.
Import('env')

# Define headers and sources.
headers = env.Glob('*.hh') + env.Glob('*.tcc') + env.Glob('*.h')
sources = env.Glob('*.cc') + env.Glob('*.cpp')

# Call the helper.
execfile(helpers.get_build_src_script(), globals())
