import sconsproject as project
from sconsproject import config

config.select(
    config.packages.boost(),
    config.packages.MPI(),
    config.packages.HDF5(),
    config.packages.PostgreSQL(),
    config.packages.sqlite3(required=False),
    config.packages.SOCI(backends=['postgres']),
    config.packages.rapidxml(),
    config.packages.Eigen(required=False),
    config.packages.libhpc(),
)

vars = project.create_variables()
vars.AddVariables(
    BoolVariable('MEMOPS', 'Log memory operations.', False),
    BoolVariable('MEMSTATS', 'Enable memory statistics.', False),
    BoolVariable('LOG', 'Enable logging.', False),
)

env = project.create_environment(vars)
env.MergeFlags('-std=c++0x')
if not env['MEMOPS']:
    env.MergeFlags('-DNMEMOPS')
if not env['MEMSTATS']:
    env.MergeFlags('-DNMEMSTATS')
if not env['LOG']:
    env.MergeFlags('-DNLOG')

project.build(
    ['base', 'modules'],
    proj_name='tao',
    env=env,
    vars=vars
)
