from sconsproject import helpers

# Bring in the SCons environment.
Import('env')

# Define our test suites. Each tuple defines a test as follows:
#
#   (suite_source, support_source0, support_source1, ..., MPI_rank_range)
#
# The support sources are optional, as is the MPI rank range.
suites = [
    ('lightcone_suite.t.hh', 'sed.cc', 'lightcone.cc', 'BSPTree.cc', 'GrahamScanConvexHull.cpp'),
    ('sed_suite.t.hh', 'sed.cc', 'lightcone.cc', 'BSPTree.cc', 'GrahamScanConvexHull.cpp'),
    ('filter_suite.t.hh', 'filter.cc', 'sed.cc', 'lightcone.cc', 'BSPTree.cc', 'GrahamScanConvexHull.cpp'),
    ('BSPTree_Test.hh', 'BSPTree.cc'),
    ('clip_suite.t.hh',),
    ('geometry_iterator.t.hh', 'GrahamScanConvexHull.cpp'),
    ('SettingReader_Test.hh', 'settingReader.cc'),
]

# Define libraries to link against.
libs = ['base'] + env.get('LIBS', [])

# Call the helper.
execfile(helpers.get_build_tests_script(), globals())
