


CREATE SEQUENCE NextJobID;
CREATE SEQUENCE NextEventID;

CREATE TABLE JOBS
(
JobID INTEGER CONSTRAINT JObs_PK PRIMARY KEY DEFAULT nextval('NextJobID'),
UIReferenceID INTEGER,
JobStatus SMALLINT DEFAULT(0),
INSERTDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
COMPELETEDATE TIMESTAMP DEFAULT NULL,
JobStatusComment VARCHAR(500) DEFAULT NULL,
XMLParams VARCHAR(5000),
JobType SMALLINT,
PBSReferenceID varchar(50) DEFAULT NULL,
PBSQueue varchar(20) DEFAULT NULL,
UserName varchar(50) DEFAULT NULL,
CONSTRAINT Jobs_UIReference UNIQUE (UIReferenceID)
);

CREATE TABLE EVENTS
(
EventID INTEGER CONSTRAINT EVENTS_PK PRIMARY KEY DEFAULT nextval('NextEventID'),
EventType SMALLINT DEFAULT(0),
ASSOCIATEDJOBID INTEGER,
EVENTDATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
EVENTDESC varchar(1000) DEFAULT NULL 
);

CREATE TABLE JobHistory
(
JobID INTEGER,
STATUSCHANGETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
NewStatus SMALLINT DEFAULT(0),
Comments varchar(1000)
);

CREATE TABLE TablesSummary
(
TableName varchar(100),
DatabaseName varchar(200),
ServerIP varchar(100),
GalaxyCount int,
TreeCount int,
MinGalaxyPerTable int,
MaxGalaxyPerTable int,
PRIMARY KEY (TableName,DatabaseName)
);



