


CREATE SEQUENCE NextJobID;
CREATE SEQUENCE NextCommandID;
CREATE SEQUENCE NextEventID;

CREATE TABLE JOBS
(
JobID INTEGER CONSTRAINT JObs_PK PRIMARY KEY DEFAULT nextval('NextJobID'),
UIReferenceID INTEGER,
SubJobIndex INTEGER DEFAULT(0),
JobStatus SMALLINT DEFAULT(0),
INSERTDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
COMPELETEDATE TIMESTAMP DEFAULT NULL,
JobStatusComment VARCHAR(500) DEFAULT NULL,
XMLParams VARCHAR(5000),
JobType SMALLINT,
PBSReferenceID varchar(50) DEFAULT NULL,
PBSQueue varchar(20) DEFAULT NULL,
UserName varchar(50) DEFAULT NULL,
database varchar(100) ,
startdate TIMESTAMP,
subjobindex INTEGER DEFAULT 0,
latestjobversion boolean DEFAULT true,
Issequential boolean DEFAULT false,
CONSTRAINT Jobs_UIReference UNIQUE (UIReferenceID)
);

CREATE TABLE EVENTS
(
EventID INTEGER CONSTRAINT EVENTS_PK PRIMARY KEY DEFAULT nextval('NextEventID'),
EventType SMALLINT DEFAULT(0),
ASSOCIATEDJOBID INTEGER,
EVENTDATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
EVENTDESC varchar(1000) DEFAULT NULL 
);

CREATE TABLE JobHistory
(
JobID INTEGER,
STATUSCHANGETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
NewStatus SMALLINT DEFAULT(0),
Comments varchar(1000)
);



CREATE TABLE COMMANDS
(
CommandID INTEGER CONSTRAINT Commands_PK PRIMARY KEY DEFAULT nextval('NextCommandID'),
UICommandID INTEGER,
UIJobID INTEGER DEFAULT(0),
CommandText varchar(50) DEFAULT NULL,
INSERTDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
COMPELETEDATE TIMESTAMP DEFAULT NULL,
ExecStatus SMALLINT DEFAULT(0),
AdditionalParams varchar(200) DEFAULT NULL
);


CREATE TABLE JobRestartList
(
JobID INTEGER CONSTRAINT JobsRestart_PK PRIMARY KEY,
UIReferenceID INTEGER, 
JobUserName varchar(50) DEFAULT NULL,
SubJobsCount INTEGER DEFAULT 1,
InsertTimeStamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
LastErrorTimeStamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
RestartCounter SMALLINT DEFAULT 0
);
